Update docker version to 1.10.0 for CircleCI build
Fixes error during CircleCI build:
ERROR: The Docker Engine version is less than the minimum required by
Compose. Your current project requires a Docker Engine of version 1.9.0
or greater.